version: '3.8'

services:
  web:
    build: ./m3u8_links
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./m3u8_links/:/usr/src/m3u8_links/
    ports:
      - 4321:8000
    env_file:
      - .env.dev
